name: Sync translations to other languages
on:
  push:
    paths:
      - "en-US/**.json"
    branches:
      - "**/stable"
      - "**/canary"
  workflow_dispatch:
jobs:
  sync_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Install jq (JSON processor)
        run: sudo apt-get install -y jq

      - name: Sync JSON files to other languages
        run: |
          # Add new files
          for lang_dir in $(find . -mindepth 1 -maxdepth 1 -type d -name "*-*" | grep -E '[a-z]{2}-[A-Z]{2}'); do
            lang=$(basename "$lang_dir")
            find en-US -type f -name "*.json" | while read file; do
              new_file="${file/en-US/$lang}"
              if [ ! -f "$new_file" ]; then
                mkdir -p "$(dirname "$new_file")"
                cp "$file" "$new_file"
                echo "Created $new_file in $lang"
              fi
            done
          done

          # Remove deleted files
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
            for lang_dir in $(find . -mindepth 1 -maxdepth 1 -type d -name "*-*" | grep -E '[a-z]{2}-[A-Z]{2}'); do
              lang=$(basename "$lang_dir")
              git diff --name-status HEAD^ HEAD | grep '^D' | awk '{print $2}' | grep '^en-US/.*\.json$' | while read file; do
                new_file="${file/en-US/$lang}"
                if [ -f "$new_file" ]; then
                  rm "$new_file"
                  echo "Deleted $new_file in $lang"
                fi
              done
            done
          else
            echo "No previous commit found, skipping deletion step."
          fi

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync translation files for other languages"

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync translation files for other languages"
          branch: "auto/sync-translations-${{ github.ref_name }}"
          title: "Sync translations in ${{ github.ref_name }}"
          body: "This PR syncs translation files for the branch **${{ github.ref_name }}**."
          assignees: ilxlodev
          reviewers: ilxlodev
          labels: syncronization, blocked
          base: ${{ github.ref_name }}