name: Sync Translations

on:
  push:
    paths:
      - 'en-US/**.json'
  workflow_dispatch:

jobs:
  sync_translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install jq (JSON processor)
        run: sudo apt-get install -y jq

      - name: Copy new JSON files to other languages
        run: |
          LANGUAGES=("es" "fr" "de" "it") # Lista de códigos de idiomas
          for lang in "${LANGUAGES[@]}"; do
            # Busca todos los archivos .json creados en la carpeta en-US
            for file in $(find en-US -type f -name "*.json"); do
              # Reemplaza "en-US" por el código de idioma en la ruta del archivo
              new_file=$(echo "$file" | sed "s/en-US/$lang/")
              # Crea el nuevo archivo si no existe
              if [ ! -f "$new_file" ]; then
                mkdir -p "$(dirname "$new_file")"
                cp "$file" "$new_file"
                echo "Created $new_file"
              fi
            done
          done

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add new translation files for other languages"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
