name: Trigger Sync Translations Workflow
on:
  workflow_dispatch:
jobs:
  trigger_sync_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync Translations Workflow
        run: |
          BRANCHES=("stable" "canary")
          for BRANCH in "${BRANCHES[@]}"; do
            gh workflow run "Sync translations to other languages" --ref $BRANCH
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger Clean orphaned files Workflow
        run: |
          BRANCHES=("stable" "canary")
          for BRANCH in "${BRANCHES[@]}"; do
            gh workflow run "Clean up orphaned translation files" --ref $BRANCH
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}